### ISSUE TITLE
Pretty-print WebGPU bitmasks values

### ISSUE THREAD

**Issue by beaufortfrancois** [greggman/webgpu-dev-extension#1]
The current representation of [GPUBuffer usage](https://gpuweb.github.io/gpuweb/#typedefdef-gpubufferusageflags) in DevTools uses bitmasks to indicate how the buffer is used. While technically accurate, this format is not readily understandable by most web developers. Examining and interpreting individual bit values within the mask requires referencing the WebGPU specification, making it a cumbersome and time-consuming process. This can hinder development workflow and understanding of buffer usage within an application.

This extension seems the perfect place to improve readability and understanding by directly displaying the flag names alongside the bit values thanks to [DevTools Custom formatters](https://firefox-source-docs.mozilla.org/devtools-user/custom_formatters/index.html). In short, they allow developers to control the display of variables within the DevTools JavaScript Console and Debugger. They need to be [manually enabled](https://www.mattzeunert.com/2016/02/19/custom-chrome-devtools-object-formatters.html#enabling-custom-formatters) in DevTools Settings.

This would be very simple to add. See https://gist.github.com/beaufortfrancois/022de328a366f6103af82e6e5160e362

<img width="1112" alt="image" src="https://github.com/greggman/webgpu-dev-extension/assets/634478/ddcce2d7-e620-40b0-9408-4c42139d0b1f">

Notes:
- Custom formatters returning `null` for `body()` is [supported in Chrome 125+](https://chromiumdash.appspot.com/commit/c6c36e479baec14186658d4536175ecaf29bb6e9).
- GPUBuffer.usage is not the only place where it would be useful. GPUTexture.usage and GPUMemoryHeapInfo.properties should also be considerered.

**Comment by beaufortfrancois** [comment]
@greggman Do you want me to start a PR or do you already have something in mind?

**Comment by greggman** [comment]
I would love to add this but I'm running into issues

1. If I try to expand an object I get an error

   <img width="561" alt="Screenshot 2024-03-27 at 11 37 46" src="https://github.com/greggman/webgpu-dev-extension/assets/234804/cbaf578e-8f5c-4e59-8836-89a0705e2dfa">

2. I tried adding a body and I got something to appear but I couldn't find any docs on how to make it match the devtools

   Example: Below `GPUBuffer` has the code from above. `GPUTexture` does not. They should have the same colors, same indentation. I was not able to find any official docs on how to do this. What elements, what css classes, etc. I can probably go into the devtools source but it would be nice to have an official doc that says "use this class for X and this element for that" so that it doesn't break in the future.

   <img width="671" alt="Screenshot 2024-03-27 at 11 40 15" src="https://github.com/greggman/webgpu-dev-extension/assets/234804/fc3364f4-e152-4909-9927-0ca4538fb57e">

3. Added properties are not shown

   If add code like this

   ```js
   buffer.myAddedProperty = 'foo';
   buffer.myAddedObject = {name: 'bar', num: 123};

   texture.myAddedProperty = 'foo';
   texture.myAddedObject = {name: 'bar', num: 123};
   ```

   `myAddedProperty` and `myAddedObject` show up for `GPUTexture` but not for `GPUBuffer` which has the custom formatter.

   <img width="730" alt="Screenshot 2024-03-27 at 11 46 40" src="https://github.com/greggman/webgpu-dev-extension/assets/234804/2417c76f-6070-4607-bcec-8b5d37a9dcca">

   The custom formatter API seems like a poorly designed API or at least requires some more docs on how to pass through things to the default formatters when you don't care.

Test code here: https://jsgist.org/?src=89816fe690e0bf43389ef954f1ae9c7c

**Comment by greggman** [comment]
I updated the example at https://jsgist.org/?src=89816fe690e0bf43389ef954f1ae9c7c to iterate through the properties and just do something different for `usage`. It helps in that the attached properties now show up but I couldn't find any way to make the styles match


I tried adding `class: '???'` and `className: '???'`, the first style is supposed to match JsonML but I get the impression the devtools are ignoring that. I can see the devtools adds `class="name"` for the name of the property and `class="name own-property" for the added properties for `GPUTexture` (the non-custom object) but I was not able to add those classes to the custom ones.

![Screenshot 2024-03-27 at 16 47 10](https://github.com/greggman/webgpu-dev-extension/assets/234804/8deacd50-7fc6-421a-bba2-fc4e80d2715b)

**Comment by beaufortfrancois** [comment]
> 1. If I try to expand an object I get an error
>    <img alt="Screenshot 2024-03-27 at 11 37 46" width="561" src="https://private-user-images.githubusercontent.com/234804/317475884-cbaf578e-8f5c-4e59-8836-89a0705e2dfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTUwOTAsIm5iZiI6MTcxMTYxNDc5MCwicGF0aCI6Ii8yMzQ4MDQvMzE3NDc1ODg0LWNiYWY1NzhlLThmNWMtNGU1OS04ODM2LTg5YTA3MDVlMmRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwODMzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDIwNjQ5MzFiY2I3MDA5NWYzOTVmYjRhZTRiYWI5ZWFhMjJmYjRlMmNmNzgwMGIwYWUwYzA1NzM2MGRjYjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cmw25ZOxLmfsBgUU2vG_63eiq0lQkhkxdWdwBEvIz5c">

That's a known issue I shared [previously](https://github.com/greggman/webgpu-dev-extension/issues/1#issue-2202150209):
- Custom formatters returning null for body() is [supported in Chrome 125+](https://chromiumdash.appspot.com/commit/c6c36e479baec14186658d4536175ecaf29bb6e9).

**Comment by greggman** [comment]
So if you return `null` from `body` then you won't get the custom display for `usage` on the expanded display? That's disappointing

**Comment by greggman** [comment]
I hacked something in.

**Comment by beaufortfrancois** [comment]
I tried it and it works great for both GPUBuffer, GPUTexture, and GPUHeapProperty. Thank you @greggman!
